### ISSUE TITLE
Setup build pipeline with AppVeyor

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog.PerformanceCounter#1]
AppVeyor-file is ready, so just need the last push

**Comment by 304NotModified** [comment]
What should I do?

**Comment by snakefoot** [comment]
Was just thinking to setup build-pipeline, so it will automatically build on commit

**Comment by 304NotModified** [comment]
Working on this

**Comment by 304NotModified** [comment]
Done and checked. Badge in readme is also working.
